### ISSUE TITLE
[Setup Help]:  Can't add bridge (no response) - docker setup

### ISSUE THREAD

**Issue by P1Rebo** [NRCHKB/node-red-contrib-homekit-docker#12]
First of all, thanks again for this great piece of software!! :-)

Maybe somebody has an idea..

Since 1-2 weeks I can't connect to the homekit objects. Maybe there have been some changes... Does anybody have an idea for me or has the same issues?

**Problem description:**
- Bridge is found while scanning.
- After adding the bridge it tries to add.
- "No response from device" comes up after 1-2 minutes.

**Setup Help**
Physical hardware device: 
- RPi4 
- docker
- node-red:latest
- homekit bridge library latest release (1.2.0)

Apple Setup:
- Apple TV 4. Gen as Home
- iPhone 8Plus / iPad Pro 2020 with latest iOS 14

HomeKit setup:
- Switch Service
- Bridge with default settings (PIN 111-11-111), allow message passthrough

Node-red container setup:
- host mode
- ports: 80:80 (TCP), 443:443 (TCP), 5353:5353 (UDP+TCP), 51827:51827 (TCP)
- priviledged mode

**Comment by P1Rebo** [comment]
Thanks for the indications! Have it working now!

I followed the link you posted and added the DNS info to the docker container and by creating a etc/docker/daemon.json as mentioned in the link:
- primary 10.0.0.2 
- second 8.8.8.8

Different error came up "getaddrinfo ENOTFOUND localhost undefined"
- Found an indication [here](https://medium.com/thepolarlab/node-js-error-getaddrinfo-enotfound-localhost-b7ee35e1bb60).
- added localhost definition to my etc/hosts file like indicated.

Everything works now. Even when I remove the DNS entries from the container...

**Comment by P1Rebo** [comment]
So here is the update.

**Reinstalled blankly**
- RPi4 4GB, arch linux latest
- /etc/hosts file is empty
- installed docker (+ portainer)
- installed your docker image
- add switch, add bridge
**Result: Can't add! Error remains.**

**Added DNS to container**
- primary 10.0.0.2
- second 8.8.8.8
**Result: Can't add! Error remains.**

**With localhost definition**
- Added localhost definition to /etc/hosts
- "127.0.0.1  localhost"
- reboot
- retry node-red container
**Result: Worked !**

**Comment by Shaquu** [comment]
@P1Rebo I am happy we solved it!
Everyone learned something.

If you want to chat with us about HomeKit or other home automations projects then join us on our Discord server.
