### ISSUE TITLE
not update nrchkb/node-red-homekit:latest-minimal in hub.docker

### ISSUE THREAD

**Issue by twocolors** [NRCHKB/node-red-contrib-homekit-docker#17]
not update nrchkb/node-red-homekit:latest-minimal in hub.docker

**Comment by Shaquu** [comment]
Hi,
I am not sure what this question is about :)
Could you clarify?

Just to let you know, I am planning to redesign docker image a little so it builds correctly every time

**Comment by twocolors** [comment]
i use docker image witch tag:latest-minimal  and this images not update in hub.docker (https://hub.docker.com/r/nrchkb/node-red-homekit/tags?page=1&ordering=last_updated) all other images is update

1.10.0-1.3.2-12-arm32v7
1.10.0-1.3.2-10-minimal-arm32v7
...

**Comment by Shaquu** [comment]
@twocolors thanks for confirmation.
As said I am aware that this issue exists 

If you know a little (more) about docker I would feel very grateful to let you know how you could contribute ;)

**Comment by Shaquu** [comment]
@twocolors you should be able to try again with the latest images

**Comment by twocolors** [comment]
not update :(

@nodered/node-red (docker)
latest-12-minimal
latest-14-minimal
latest-minimal (node14)

you don't build this images

**Comment by Shaquu** [comment]
@twocolors have a look here
https://hub.docker.com/r/nrchkb/node-red-homekit/tags

Should be plenty of tags for you.

**Comment by twocolors** [comment]
thx, wait node-red 2.0.3
