### ISSUE TITLE
node.js 16 support

### ISSUE THREAD

**Issue by ferdinandhelmer** [NRCHKB/node-red-contrib-homekit-docker#79]
Hi, 
I am very happily using the latest image, however when trying to install a node-red package like nodered-contrib-ring-alarm it requires node.js >= 16.x, the latest image here is based on node.js 14.x
What would be the best way to "lift" the docker image to support node.js 16.x packages?
I put this as an issue in order to either get you expert opinion in how to do it on my end or on the official image side.

**Comment by caius88** [comment]
Hi,
i need the newer version of node.js too. Please update this image soon :)
Thank you

**Comment by Shaquu** [comment]
All tags

https://hub.docker.com/r/nrchkb/node-red-homekit/tags

**Comment by Shaquu** [comment]
There is also version node NodeJS 18
